### PR TITLE
Fixed concurrency issue

### PR DESCRIPTION
**Pull request by shishir127**
I think there's a concurrency issue in the rate limiting logic. Please let me know what you think about this fix. This is important because there's a [sidekiq-rate-limiter](https://github.com/enova/sidekiq-rate-limiter) gem that uses the redis_rate_limiter gem. Sidekiq rate limiter's rate limiting won't work as well without this fix.

### CODE REVIEW

**Comment by shishir127** [comment]
I think the problems occurs when 
1) The size of the rate limiting redis list is `(limit -1)`.
2) 2 or more threads check if `exceeded?` at the same time and all threads are told that they can fire more requests.
3) 2 or more threads call `add` at almost the same instant and end up violating the rate limits.

How I think we can ensure this doesn't happen without making too many changes
* Replacing the redis multi with a mutex so that at a time only 1 thread is writing to the redis rate limit list.
* Checking if `exceeded?` after obtaining the mutex lock for cases where the lock is obtained after the rate limit exceeded.
* The extra call to `exceeded?` is IMO required because otherwise we will get a mutex lock and then check if `exceeded?`.
I'm happy to replace this implementation with some other mechanism or make any another changes.

**Comment by seanxiesx** [comment]
Thanks for elaborating.

This Redis-backed rate limiter was meant to be an approximate distributed rate limiter, i.e. the failure case you mentioned can happen, and will happen, occasionally. If you have a very high throughput service where correctness is extremely important to you, I might recommend using either an in-memory rate limiter, for example: https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/RateLimiter.java, or rolling out your own rate limiter service.

The main reason I don't think your fix is the right approach is because it does nothing to address multiple ruby processes from the issue you pointed out anyway. For example, say you had 2 machines, each running a ruby process using this rate limiter, then each process might check `exceeded?` at the same time, and proceed to manipulate the rate limiter list but violate the rate limit (if only 1 more permit was allowed at that time).

Perhaps the right approach here is to make the rate limiter module in https://github.com/enova/sidekiq-rate-limiter pluggable, and implement a better rate limiter for your use case?

**Comment by shishir127** [comment]
👍 . My main aim to was to get the rate limiting in the sidekiq rate limiter gem corrected. Thanks for your help.

**Comment by bwthomas** [comment]
"Perhaps the right approach here is to make the [sidekiq-rate-limiter](https://github.com/enova/sidekiq-rate-limiter) pluggable, and implement a better rate limiter for your use case?"

+1 for this strategy. Pull requests welcome, otherwise I'll look at this in the future.

**Pull request closed without merging**
